/**
 * generated by Xtext 2.19.0
 */
package org.eclipse.mydsl.ide;

import org.eclipse.mydsl.ide.AbstractMyDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MyDslIdeModule extends AbstractMyDslIdeModule {
}
