/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.SchoolModelImpl <em>School Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.SchoolModelImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSchoolModel()
   * @generated
   */
  int SCHOOL_MODEL = 0;

  /**
   * The feature id for the '<em><b>Schools</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHOOL_MODEL__SCHOOLS = 0;

  /**
   * The number of structural features of the '<em>School Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHOOL_MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.SchoolImpl <em>School</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.SchoolImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSchool()
   * @generated
   */
  int SCHOOL = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHOOL__NAME = 0;

  /**
   * The feature id for the '<em><b>Persons</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHOOL__PERSONS = 1;

  /**
   * The number of structural features of the '<em>School</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHOOL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.PersonImpl <em>Person</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.PersonImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getPerson()
   * @generated
   */
  int PERSON = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__NAME = 0;

  /**
   * The number of structural features of the '<em>Person</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.StudentImpl <em>Student</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.StudentImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getStudent()
   * @generated
   */
  int STUDENT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STUDENT__NAME = PERSON__NAME;

  /**
   * The feature id for the '<em><b>Registration Num</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STUDENT__REGISTRATION_NUM = PERSON_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Teachers</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STUDENT__TEACHERS = PERSON_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Student</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STUDENT_FEATURE_COUNT = PERSON_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.TeacherImpl <em>Teacher</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.TeacherImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getTeacher()
   * @generated
   */
  int TEACHER = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEACHER__NAME = PERSON__NAME;

  /**
   * The number of structural features of the '<em>Teacher</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEACHER_FEATURE_COUNT = PERSON_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.SchoolModel <em>School Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>School Model</em>'.
   * @see org.xtext.example.mydsl.myDsl.SchoolModel
   * @generated
   */
  EClass getSchoolModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.SchoolModel#getSchools <em>Schools</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Schools</em>'.
   * @see org.xtext.example.mydsl.myDsl.SchoolModel#getSchools()
   * @see #getSchoolModel()
   * @generated
   */
  EReference getSchoolModel_Schools();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.School <em>School</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>School</em>'.
   * @see org.xtext.example.mydsl.myDsl.School
   * @generated
   */
  EClass getSchool();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.School#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.School#getName()
   * @see #getSchool()
   * @generated
   */
  EAttribute getSchool_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.School#getPersons <em>Persons</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Persons</em>'.
   * @see org.xtext.example.mydsl.myDsl.School#getPersons()
   * @see #getSchool()
   * @generated
   */
  EReference getSchool_Persons();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Person <em>Person</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Person</em>'.
   * @see org.xtext.example.mydsl.myDsl.Person
   * @generated
   */
  EClass getPerson();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Person#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Person#getName()
   * @see #getPerson()
   * @generated
   */
  EAttribute getPerson_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Student <em>Student</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Student</em>'.
   * @see org.xtext.example.mydsl.myDsl.Student
   * @generated
   */
  EClass getStudent();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Student#getRegistrationNum <em>Registration Num</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Registration Num</em>'.
   * @see org.xtext.example.mydsl.myDsl.Student#getRegistrationNum()
   * @see #getStudent()
   * @generated
   */
  EAttribute getStudent_RegistrationNum();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.Student#getTeachers <em>Teachers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Teachers</em>'.
   * @see org.xtext.example.mydsl.myDsl.Student#getTeachers()
   * @see #getStudent()
   * @generated
   */
  EReference getStudent_Teachers();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Teacher <em>Teacher</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Teacher</em>'.
   * @see org.xtext.example.mydsl.myDsl.Teacher
   * @generated
   */
  EClass getTeacher();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.SchoolModelImpl <em>School Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.SchoolModelImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSchoolModel()
     * @generated
     */
    EClass SCHOOL_MODEL = eINSTANCE.getSchoolModel();

    /**
     * The meta object literal for the '<em><b>Schools</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCHOOL_MODEL__SCHOOLS = eINSTANCE.getSchoolModel_Schools();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.SchoolImpl <em>School</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.SchoolImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSchool()
     * @generated
     */
    EClass SCHOOL = eINSTANCE.getSchool();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCHOOL__NAME = eINSTANCE.getSchool_Name();

    /**
     * The meta object literal for the '<em><b>Persons</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCHOOL__PERSONS = eINSTANCE.getSchool_Persons();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.PersonImpl <em>Person</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.PersonImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getPerson()
     * @generated
     */
    EClass PERSON = eINSTANCE.getPerson();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON__NAME = eINSTANCE.getPerson_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.StudentImpl <em>Student</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.StudentImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getStudent()
     * @generated
     */
    EClass STUDENT = eINSTANCE.getStudent();

    /**
     * The meta object literal for the '<em><b>Registration Num</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STUDENT__REGISTRATION_NUM = eINSTANCE.getStudent_RegistrationNum();

    /**
     * The meta object literal for the '<em><b>Teachers</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STUDENT__TEACHERS = eINSTANCE.getStudent_Teachers();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.TeacherImpl <em>Teacher</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.TeacherImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getTeacher()
     * @generated
     */
    EClass TEACHER = eINSTANCE.getTeacher();

  }

} //MyDslPackage
