/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>School Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SchoolModel#getSchools <em>Schools</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSchoolModel()
 * @model
 * @generated
 */
public interface SchoolModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Schools</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.School}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Schools</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSchoolModel_Schools()
   * @model containment="true"
   * @generated
   */
  EList<School> getSchools();

} // SchoolModel
