/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Student</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Student#getRegistrationNum <em>Registration Num</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Student#getTeachers <em>Teachers</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getStudent()
 * @model
 * @generated
 */
public interface Student extends Person
{
  /**
   * Returns the value of the '<em><b>Registration Num</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Registration Num</em>' attribute.
   * @see #setRegistrationNum(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getStudent_RegistrationNum()
   * @model
   * @generated
   */
  int getRegistrationNum();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Student#getRegistrationNum <em>Registration Num</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Registration Num</em>' attribute.
   * @see #getRegistrationNum()
   * @generated
   */
  void setRegistrationNum(int value);

  /**
   * Returns the value of the '<em><b>Teachers</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Teacher}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Teachers</em>' reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getStudent_Teachers()
   * @model
   * @generated
   */
  EList<Teacher> getTeachers();

} // Student
