/**
 * generated by Xtext 2.19.0
 */
package org.eclipse.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.mydsl.myDsl.Model#getEigenschaften <em>Eigenschaften</em>}</li>
 * </ul>
 *
 * @see org.eclipse.mydsl.myDsl.MyDslPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Eigenschaften</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.mydsl.myDsl.Eigenschaft}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Eigenschaften</em>' containment reference list.
   * @see org.eclipse.mydsl.myDsl.MyDslPackage#getModel_Eigenschaften()
   * @model containment="true"
   * @generated
   */
  EList<Eigenschaft> getEigenschaften();

} // Model
