/*
 * generated by Xtext 2.19.0
 */
package org.eclipse.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.mydsl.ui.internal.MydslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MydslActivator.getInstance().getInjector("org.eclipse.mydsl.MyDsl");
	}

}
